[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local
address = /api.locket.camera/127.0.0.1
remote-dns = 8.8.8.8

[Rule]
DOMAIN-SUFFIX,locket.camera,DIRECT
FINAL,DIRECT

[Script]
HoangPhu_Full = type=http-response,pattern=^https?:\/\/api\.locket\.camera\/(v\d+)\/(user\/profile|subscriptions|account\/status),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/vuong2023/shad/main/modules/HoangPhu_Locket_Full.js

[MITM]
hostname = api.locket.camera, auth.locket.camera
