#!name=Locket Gold (by HoangPhu)
#!desc=Mở khóa Full Gold Bản quyền HoangPhu.
#!author=HoangPhu
#!system=iOS

[MITM]
hostname = %APPEND% api.locket.camera, auth.locket.camera

[Script]
HoangPhu_Locket = type=http-response,pattern=^https?:\/\/api\.locket\.camera\/(v\d+)\/(user\/profile|subscriptions|account\/status),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/hoangphu1106/Locket_Gold/main/Locket_Gold_HoangPhu.js

[General]
force-http-engine-hosts = %APPEND% api.locket.camera
